export const workflowInstruction = `This is an OpenCode /workflow request. First read workflow_reference for the current connected model pool and configured subagent roles. Choose the smallest sufficient team yourself unless the user specifies its size or assignments. Give a brief plain-language explanation of each assignment and why its model fits the reasoning, capability, and reported cost needs. Do not claim a model is cheapest when prices or capabilities are unknown.
Use workflow with a declarative plan: summary and tasks containing id, label, task, reason, exact model, optional agentType, and dependsOn task IDs. The engine creates the JavaScript privately. Do not write a workflow script with write/edit/bash, print orchestration code, or narrate internal setup. Use script mode only when the user explicitly asks for custom JavaScript orchestration.
The workflow engine already supplies orchestration. Do not load unrelated loop, Ralph, or Claude scheduling skills for this request. Task-specific project instructions and relevant skills still apply. Honor explicit user model/count assignments; set userRequestedModel only for an actual explicit user request. Background execution is the default for plans; the sidebar and /workflows show live progress. Wait for the final result notification without redundant polling or declaring unfinished work done.`;

export const goalInstruction = `This is an explicit /workflow-goal request. Use workflow_goal, not workflow or another goal/loop plugin. With an objective, use action start and preserve the user's full objective and constraints verbatim. With no arguments use status. Recognize status, history, pause, resume, stop, and edit <revised objective> as controls. Never create a goal from a status question or silently replace an existing goal. The persistent supervisor will plan successive workflows and independently verify the fixed acceptance criteria; it has no goal-wide token, cycle, or time ceiling. Individual workflow safeguards and user permissions still apply. Ultracode is compatible: it configures orchestration/effort, not a second goal owner. Do not implement the goal yourself, launch an extra workflow, load scheduling skills, or poll after starting. Tell the user how to open /workflow-goals for native controls and /workflows for child runs. Completion can only be set by the supervisor's evidence gate, not by this conversation.`;

export const commands = {
  workflow: { description: "Plan the right team and run a workflow with live progress", template: "$ARGUMENTS" },
  "workflow-goal": { description: "Keep running workflows until a goal is verified; status/pause/resume/stop/edit/history", template: "$ARGUMENTS" },
  "workflows-chat": { description: "Chat fallback: list workflow runs and progress", template: "Use workflow_runs with action list to show this session's runs. $ARGUMENTS" },
  "workflow-config-chat": { description: "Chat fallback: choose workflow models and limits", template: "Use workflow_config show to list exact connected provider/model IDs and current settings. Help the user choose allowed models with the question tool if needed, then use workflow_config set. User request: $ARGUMENTS" },
  "ultracode-chat": { description: "Chat fallback: control automatic workflows for this session", template: "Use workflow_mode to show or change this session's automatic workflow setting as requested. Enabling ultracode uses exact xhigh reasoning only on models that support it. User request: $ARGUMENTS" },
  "workflow-stop": { description: "Stop a workflow", template: "Use workflow_runs stop for the requested run ID, or the latest active run in this session when omitted: $ARGUMENTS" },
};
