export const workflowInstruction = `This is an OpenCode /workflow request. First read workflow_reference for the current connected model pool and configured subagent roles. Choose the smallest sufficient team yourself unless the user specifies its size or assignments. Give a brief plain-language explanation of each assignment and why its model fits the reasoning, capability, and reported cost needs. Do not claim a model is cheapest when prices or capabilities are unknown.
Use workflow with a declarative plan: summary and tasks containing id, label, task, reason, exact model, optional agentType, and dependsOn task IDs. The engine creates the JavaScript privately. Do not write a workflow script with write/edit/bash, print orchestration code, or narrate internal setup. Use script mode only when the user explicitly asks for custom JavaScript orchestration.
The workflow engine already supplies orchestration. Do not load unrelated loop, Ralph, or Claude scheduling skills for this request. Task-specific project instructions and relevant skills still apply. Honor explicit user model/count assignments; set userRequestedModel only for an actual explicit user request. Background execution is the default for plans; the sidebar and /workflows show live progress. Wait for the final result notification without redundant polling or declaring unfinished work done.`;

export const commands = {
  workflow: { description: "Plan the right team and run a workflow with live progress", template: "$ARGUMENTS" },
  "workflows-chat": { description: "Chat fallback: list workflow runs and progress", template: "Use workflow_runs with action list to show this session's runs. $ARGUMENTS" },
  "workflow-config-chat": { description: "Chat fallback: choose workflow models and limits", template: "Use workflow_config show to list exact connected provider/model IDs and current settings. Help the user choose allowed models with the question tool if needed, then use workflow_config set. User request: $ARGUMENTS" },
  "ultracode-chat": { description: "Chat fallback: control automatic workflows for this session", template: "Use workflow_mode to show or change this session's automatic workflow setting as requested. Enabling ultracode uses exact xhigh reasoning only on models that support it. User request: $ARGUMENTS" },
  "workflow-stop": { description: "Stop a workflow", template: "Use workflow_runs stop for the requested run ID, or the latest active run in this session when omitted: $ARGUMENTS" },
};
